### ISSUE TITLE
Filters in feedback are not processed

### ISSUE THREAD

**Issue by a-kempka** [ndunand/moodle-qtype_matrix#67]
When inserting any text into an item's feedback the text does not seem to be processed by filters:

* inserting Tex notation into the item's feedback,  e.g.``$$ \sqrt(x) $$``, shows the source code instead of the processed Tex
* inserting MathType via the Wiris Editor only shows the source, e.g. ``«math xmlns=¨http://www.w3.org/1998/Math/MathML¨»«msqrt»«mi»x«/mi»«/msqrt»«/math»``,  instead of the rendered formula
* HTML formatted with Atto however works, tis includes MathML as 
`<math>
  <msqrt>
    <mn>3</mn>
  </msqrt>
</math>`
* inserting Generico-Templates only shows the code for the template instead of its rendered content

This is unexpected, since the feedback is formatted with an Atto Editor supplying options for formatting. This is inconsistent as TeX and filters work within the items' text or the question's description

**Comment by minhduchoang195** [comment]
The main reason for this is that the feedback in the matrix question renderer (question/type/matrix/renderer.php) has not been reformulated so that the installed Moodle filters can recognize and process these texts. The short name and description of each line have been formatted by the format_text function, so these filters can be applied to short names and descriptions, but not to feedback.

I created the pull request 69 (https://github.com/ndunand/moodle-qtype_matrix/pull/69) to resolve this issue.

**Comment by NicoAlexH** [comment]
Fixed by #69, thank you @minhduchoang195 !
